# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{drizzle}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Padraig O'Sullivan"]
  s.date = %q{2011-04-13}
  s.description = %q{An interface to Drizzle for Ruby that uses libdrizzle}
  s.email = %q{osullivan.padraig@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/drizzle.rb",
    "lib/drizzle/connection.rb",
    "lib/drizzle/drizzle.rb",
    "lib/drizzle/exceptions.rb",
    "lib/drizzle/ffidrizzle.rb",
    "lib/drizzle/result.rb",
    "test/helper.rb",
    "test/test_basic.rb",
    "test/test_complex.rb"
  ]
  s.homepage = %q{http://github.com/posulliv/drizzle-ruby}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{drizzle-ruby}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A ruby interface to Drizzle using libdrizzle}
  s.test_files = [
    "test/helper.rb",
    "test/test_basic.rb",
    "test/test_complex.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

